# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_url = "https://app.vagrantup.com/ubuntu/boxes/xenial64"
  # config.vm.define "ubuntu1604"
  config.vm.hostname = "ubuntu1604"
  config.vm.box_check_update = false

  # Port forwarding
  config.vm.network "forwarded_port", guest: 10039, host: 10039 # http://ubuntu:10039/wps/portal
  config.vm.network "forwarded_port", guest: 10200, host: 10200 # http://localhost:10200/ibm/wizard

  # Private network
  config.vm.network "private_network", ip: "10.0.0.10"

  # Sync folder
  config.vm.synced_folder "sync/", "/home/vagrant/sync-data"

  # Provider-specific configuration
  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu1604"
    vb.memory = "2048"
  end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
